# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------
QT += sql
TEMPLATE = app
TARGET = testQTHIK
DESTDIR = ../../../../质控组/ZJ17listen/x64/Debug
CONFIG += debug
LIBS += -L"$(Qt_LIBPATH_)" \
    -l$(Qt_LIBS_) \
    -l/"$(INHERIT)/" \
    -lMvCameraControl \
    -lopencv_world349d
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += debug
UI_DIR += .
RCC_DIR += .
